### ISSUE TITLE
Plugin fails when I set stage parameter in command line

### ISSUE THREAD

**Issue by gulbinas** [ubaniabalogun/serverless-package-python-functions#27]
Command ```sls deploy -s prod``` fails with ```Error: ENOENT: no such file or directory, open '_build/AAAAA-dev-AAAAA.zip'```

Looks like it generates proper files but tries to deploy dev env files

related: https://github.com/serverless/serverless/issues/4456

My config file:

```

frameworkVersion: ">=v1.12"


custom:
  profile: serverless-deployer
  region: eu-west-1
  stage: dev
  pkgPyFuncs: # plugin configuration
    buildDir: _build
    requirementsFile: 'requirements.txt'
    # globalRequirements:
    #   - ./requirements.txt
    globalIncludes:
      - ./lib
    #cleanup: true
    #useDocker: false
    useDocker: true
    dockerImage: lambci/lambda:build-python2.7

```

```
[justinas@AAAA-mac-6 AAAA (develop *$)]$ SLS_DEBUG=* sls deploy -s prod
Serverless: Load command run
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command emit
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: [serverless-package-python-functions] Packaging using Docker container...
Serverless: [serverless-package-python-functions] Using Docker Server Version 17.09.0-ce & Client Version 17.09.0-ce

Serverless: [serverless-package-python-functions] Creating Docker container "serverless-package-python-functions"...
Serverless: [serverless-package-python-functions] Container already exists. Reusing.
Serverless: [serverless-package-python-functions] Docker setup completed
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...


Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...

Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: [serverless-package-python-functions] Packaging AAAAA-prod-AAAAA...
Serverless: Packaging service...

  Error --------------------------------------------------

  ENOENT: no such file or directory, open '_build/AAAAA-dev-AAAAA.zip'

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

Error: ENOENT: no such file or directory, open '_build/AAAAA-dev-AAAAA.zip'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at AwsCompileFunctions.compileFunction (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:290:24)
    at serverless.service.getAllFunctions.forEach (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:332:39)
    at Array.forEach (native)
    at AwsCompileFunctions.compileFunctions (/usr/local/lib/node_modules/serverless/lib/plugins/aws/package/compile/functions/index.js:332:8)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at Deploy.BbPromise.bind.then.then (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:117:50)
From previous event:
    at Object.before:deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/deploy/deploy.js:107:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.6.0
     Serverless Version:     1.23.0
```

**Comment by ubaniabalogun** [comment]
Hey @gulbinas Thanks for the details report!
Can you please share with me the configuration of your functions in the serverless.yml file?

My suspicion is either that the function name isn't being set explicitly, or the stage is not being set in the function name. 
Thanks,

**Comment by gulbinas** [comment]
You were right. Problem solved.

Correct function declaration for reference
```
AAAAA:
  handler: handler. AAAAA
  description: Function to process AAAAA queries
  package:
    include:
      - src/AAAAA
    artifact: ${self:custom.pkgPyFuncs.buildDir}/${self:service}-${self:provider.stage}-AAAAA.zip
```
